baseURL = "http://example.org/"
languageCode = "ja"
title = "choiyakiBlog"
contentDir = "post"
disableKinds = ["RSS", "sitemap"]
theme = "fuji"
publishDir = "docs"
[taxonomies]
category = "category"
tag = "tags"