baseURL = "http://example.org/"
languageCode = "ja"
title = "choiyakiBlog"
contentDir = "post"
disableKinds = ["RSS", "sitemap"]
theme = "mainroad"
publishDir = "docs"
[taxonomies]
category = "categories"
tag = "tags"
[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
weight = 10