baseURL = "https://choiyaki.com"
languageCode = "ja"
# title = "choiyakiBlog"
title = "iPhoneと本と数学となんやかんやと"
contentDir = "post"
disableKinds = ["RSS", "sitemap"]
theme = "mainroad"
publishDir = "docs"
rssLimit = 20
copyright = "2021 Atsushi Yoshida All rights reserved"

[author]
	name = "choiyaki"
	email = "choiyaki@gmail.com"

[taxonomies]
category = "categories"
tag = "tags"
[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
[related]
threshold = 80
includeNewer = true
toLower = false
[outputs]
  home = [ "HTML", "RSS" ]
  page = [ "HTML", "AMP" ] # if you want AMP enable.

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
weight = 10

[Params.style.vars]
  highlightColor = "#008080" # Override highlight color
  
  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.sidebar]
  single = "left" # Configure layout for single pages
  home = "left" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]