[[redirects]]
from = "https://604cbc142736280007dda6d0--musing-hawking-60eba8.netlify.app/"
query = {p = ":p"}
to = "https://604cbc142736280007dda6d0--musing-hawking-60eba8.netlify.app/aaa"
status = 301