[[redirects]]
from = "https://604cc7fdc209fd0007e7692e--musing-hawking-60eba8.netlify.app/blog/"
to = "https://604cc7fdc209fd0007e7692e--musing-hawking-60eba8.netlify.app/article/"
status = 301
force = true