[[redirects]]
from = "https://604cbc142736280007dda6d0--musing-hawking-60eba8.netlify.app/blog/*"
to = "https://604cbc142736280007dda6d0--musing-hawking-60eba8.netlify.app/article/:slate"
status = 301